#!/bin/bash
# Shell script to convert Fahrenheit to Celsius Temperature 

echo -n "Enter temperature (F) : "
read tf
# formula Tc=(5/9)*(Tf-32) 
tc=$(echo "scale=2;(5/9)*($tf-32)"|bc)
echo "$tf F = $tc C"
